"""authentication with concrete base class

Revision ID: bb66e9c14333
Revises: 
Create Date: 2024-09-05 16:29:22.855167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb66e9c14333'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('fid', sa.String(length=36), nullable=False, comment='Code file storing the file.'),
    sa.Column('filename', sa.String(length=256), nullable=True, comment='Name of uploaded file'),
    sa.PrimaryKeyConstraint('fid'),
    sa.UniqueConstraint('fid')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=24), nullable=True, comment='Username of user.'),
    sa.Column('first_name', sa.String(length=24), nullable=True, comment='Firstname of the user'),
    sa.Column('last_name', sa.String(length=24), nullable=True, comment='Lastname of the user'),
    sa.Column('email', sa.String(length=56), nullable=True, comment='Email of the user.'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='Password'),
    sa.Column('password', sa.String(length=40), nullable=True, comment='Password table column'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('upload')
    # ### end Alembic commands ###
