"""default autoincreament sr_no to 0

Revision ID: bffddcdf847d
Revises: bd6f8e6d8bdb
Create Date: 2024-09-05 16:32:53.032380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffddcdf847d'
down_revision: Union[str, None] = 'bd6f8e6d8bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
