"""added auto increment

Revision ID: bd6f8e6d8bdb
Revises: bb66e9c14333
Create Date: 2024-09-05 16:32:11.365673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6f8e6d8bdb'
down_revision: Union[str, None] = 'bb66e9c14333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sr_no', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sr_no')
    # ### end Alembic commands ###
